version: "3.8"

services:
  mealie:
    user: "1000"
    image: ghcr.io/mealie-recipes/mealie:v1.4.0
    container_name: mealie 
    restart: unless-stopped
    volumes:
      - ./data:/app/data/
    environment:
      ALLOW_SIGNUP: true
      PUID: 1000
      PGID: 1000
      TZ: America/Chicago
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://mealie.rileymathews.com
    labels:
      - traefik.enable=true
      - traefik.http.routers.mealie.rule=Host(`mealie.rileymathews.com`)
      - traefik.http.routers.mealie.tls.certresolver=le
      
